### ISSUE TITLE
What does the failing badge mean?

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzzExports#52]
@jwokaty, does the failing badge mean an error in the R code?

**Comment by jwokaty** [comment]
It means that the GitHub Action workflow is failing/red. It doesn't say so explicitly, but I think this is for the default branch, main. (I am testing on another branch if you check the actions tab, which is currently passing. However, I am not convinced that it is working correctly, but I am going to merge the changes. I will run it again and we can see if the status will change to good/green.)

**Comment by jwokaty** [comment]
The badge is now green since the action in the default branch is passing. I still need to fix the action so that it only updates when the contents of the file excluding the header have changed, which I'll fix in #36.

I hope this answers your question/concern. I'm going to close the issue, but feel free to reopen or ask on slack if you have additional questions.
